"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# INICJALIZACJA DJANGO-ENVIRON
# Ten blok kodu odczytuje zmienne z pliku .env (lokalnie)
# lub ze zmiennych środowiskowych (na serwerze Render)
# ==============================================================================
env = environ.Env(
    # Ustawienie domyślnej wartości i typu dla DEBUG
    DEBUG=(bool, False)
)
# Wskazanie ścieżki do pliku .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# ==============================================================================
# USTAWIENIA BEZPIECZEŃSTWA I KONFIGURACJI
# ==============================================================================

# Klucz bezpieczeństwa odczytywany ze środowiska
SECRET_KEY = env('SECRET_KEY')

# Tryb DEBUG odczytywany ze środowiska (domyślnie False, jeśli go nie ma)
DEBUG = env('DEBUG')

# Konfiguracja dozwolonych hostów dla Render i lokalnie
ALLOWED_HOSTS = ['127.0.0.1']

RENDER_EXTERNAL_HOSTNAME = env.str('RENDER_EXTERNAL_HOSTNAME', default=None)
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# ==============================================================================
# DEFINICJE APLIKACJI I MIDDLEWARE
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Poprawne miejsce dla Whitenoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# ==============================================================================
# BAZA DANYCH
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
# ==============================================================================

DATABASES = {
    # Odczytuje konfigurację bazy z jednej zmiennej DATABASE_URL
    'default': env.db(),
}


# ==============================================================================
# WALIDACJA HASEŁ
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================================================================
# INTERNACJONALIZACJA
# https://docs.djangoproject.com/en/4.0/topics/i18n/
# ==============================================================================

LANGUAGE_CODE = 'pl'
TIME_ZONE = 'Europe/Warsaw'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# ==============================================================================
# PLIKI STATYCZNE (CSS, JS) I MEDIA (UPLOADOWANE PLIKI)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
# ==============================================================================

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # Poprawiona nazwa zmiennej

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Konfiguracja dla Whitenoise w środowisku produkcyjnym
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==============================================================================
# USTAWIENIA DOMYŚLNE
# ==============================================================================

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'